spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false